# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Area' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Area
  pod 'Toast-Swift', '~> 5.0.0'
  pod 'UnderKeyboard', '~> 13.0'
  pod 'Alamofire', '~> 5.2'

end
